### ISSUE TITLE
Onion skin toggle is off center

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#1]
This element in the sidebar is currently too high

**Comment by le717** [comment]
Are you planning on having multiple sidebar toggle buttons or just this one?

**Comment by BoatsAreRockable** [comment]
Not at the current time but it would be good to have a simple way of adding more. You might be interested to see BA's feature roadmap: https://docs.google.com/spreadsheets/d/1_3Ku9bAIWgeZ_Ddc5hghslm8VTZf0mxwGsEqefcuQP8/pubhtml

**Comment by le717** [comment]
Oh yes, that roadmap is very interesting and helpful! Thanks!
