### ISSUE TITLE
Remove references to x64 build from installer

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#110]
Since x64 builds have been dropped the previous combined x86 and x64 Windows installer needs to be updated to remove references to x64 builds.

**Comment by le717** [comment]
When was the x64 build dropped? I know in #79 I merged the two into one installer and advocated dropping x64, but I did not know it ever happened (unless it did just now).

**Comment by BoatsAreRockable** [comment]
My bad, I incorrectly recalled agreeing to drop it in a more official manner.

**Comment by le717** [comment]
In that case, we'll go ahead and drop it! It at least makes the installer that much smaller. :P
