### ISSUE TITLE
The last frame doesn't display when selected after deleting frame

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#114]
If an individual frame is deleted using the icons on the framereel the last frame captured on the framereel does not display correctly. Additionally clicking frames on the framereel appears to display the wrong image. All of the frames display correctly during playback. I'll hopefully be taking a look at this tomorrow but @le717 if you have any time to check this out that would be fantastic.

In the example below pieces of paper with the numbers 1 - 7 were captured and the sheet with "4" written on it was deleted.

As you can see selecting the thumbnail with 5 on it actually previews frame 6:
![screenshot 156](https://cloud.githubusercontent.com/assets/8095888/13092618/db39a69e-d4f8-11e5-9de2-10cbd7a3a429.png)

The last frame does not display at all:
![screenshot 157](https://cloud.githubusercontent.com/assets/8095888/13092619/db927ff8-d4f8-11e5-9ea9-5af71dfa5f93.png)

**Comment by le717** [comment]
Remember when I said the deletion system is good as-is? Well, I kinda lied. It _works_ but is buggy and broken as can be. I have hit this bug so many times it is not funny and I can't fix it. Truthfully, I'm very close to submitting code to completely remove those buttons, keep only the "undo last frame" code, and push a take system (#37) to a higher milestone. Rioforce and I have already talked about this, and even a basic take system will be the ideal fix.

**Comment by BoatsAreRockable** [comment]
Thanks for coming clean, so to speak! Sorry for the headaches this must of caused you...
In regards to the take system, my understanding is that are you saying that once that is implemented something similar to this deletion system could be reimplemented.

**Comment by le717** [comment]
More like a take system would be the deletion system we needed. I have a blueprint of how it should work, and after critically thinking it over, I found it will most likely provide the proper way to manage frame deletion and saving.

**Comment by le717** [comment]
Advice: go ahead and tell remove this buttons and kill this buggy mess as it never worked anyway. I have a commit that does so on my fork, issue-83 branch. Just copy the changes I made and be done with it.

**Comment by le717** [comment]
Nullified by #124, closing.
