### ISSUE TITLE
Can I be a repo contributor?

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/animator#121]
By making me a contributor, I can help sort issues, but most importantly, I can create branches on this repo, branches you can easily pull and push to yourself. It would make upgrading to NW.js 0.13 _much easier_ as we can both pull the others work and build on it. Initially impressions are it's going to be too much for one person, and me working on a fork will make the upgrade that much more complicated.

**Comment by BoatsAreRockable** [comment]
Yes, I shall make you a contributor :)

**Comment by le717** [comment]
Thank you! :smiley:
