### ISSUE TITLE
NW.js vs Electron

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#128]
From what I've seen so far, upgrading to NW.js version 0.13 #108 is going to require a fair bit of work. It seems a good time to consider whether there are any advantages to moving this program from NW.js over to [Electron](https://github.com/atom/electron). I can't see any major advantages of doing so but I'd welcome any comments.

**Comment by le717** [comment]
I say stay with NW.js. It'd probably be more work to totally switch engines than it would be to update to 0.13.

**Comment by BoatsAreRockable** [comment]
@le717 0.13's improvements and the change to more rapid releases seem to address most of the concerns I had with NW.js anyway. Therefore stay we shall!
