### ISSUE TITLE
Remove first splash screen

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#14]
When the program is opened, a splash screen is seen for a second, not enough time to read. Then, it opens up to the project manager box, which says the same thing as the splash screen (the name and the creator), along with other stuff. I think the first splash screen should be removed in order to save time, and because it really isn't needed, seeing as all of it's information is already seen on the next screen.

**Comment by BoatsAreRockable** [comment]
I agree the initial splash screen is unnecessary - unless anyone else objects I will remove it. Also I shortly intend to overall the appearance of the menu screen

**Comment by le717** [comment]
:+1: for splash screen removal.
