### ISSUE TITLE
User notification system

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/animator#19]
There are a number of error and success messages that ought to be displayed to the user. However, an `alert()` box creates a bad UX. What we need is a simple, elegant, unobtrusive system to display the messages.

We have two options:
1. The HTML5 [Notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) [API](http://www.paulund.co.uk/html5-notifications). It is simple and works well, but it looks different everywhere, can't be styled, and you cannot denote what type of message (success, general, error) is being displayed.
2. Roll our own, which is not that hard at all. There could be a div hidden at the top of the screen. When triggered, it will appear for a short bit to display the message and go away automatically. We can have 3 APIs: success, general, and warning. Each one can apply styling specific to the error type (success green, general blue, error red).

I am leaning more towards rolling our own for customization purposes, but I'll leave it up to you which should be used.

**Comment by BoatsAreRockable** [comment]
I think that developing our own notification system would be better. `alert()` boxes are definitely out of the question, while to me the HTML5 notifications look like something that would appear when the app was minimized - particularly those NW.js produces in Windows 10. I can think of a number of cases (such as #15) where having a proper notification system would be excellent.

**Comment by le717** [comment]
While #15 would certainly benefit from a custom system, the initial implementation (as described in this issue) would not have any interaction in it, only display. However, we can look into expanding it afterward.

**Comment by BoatsAreRockable** [comment]
That sounds good to me!

**Comment by le717** [comment]
BTW, I've already have this mostly implemented and it should be ready this afternoon. ;)

**Comment by BoatsAreRockable** [comment]
Excellent :smile:
