### ISSUE TITLE
Onion skinning broken

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#24]
@le717 mentions fixing this in #22 but I feel it would be a good idea for this to be documented as a separate issue due to its importance.

**Comment by le717** [comment]
Let me clarify: onion skinning broke because of the rewritten code and I fixed it to function but not properly work. I have no intention on fixing it proper in #22 (that is out of scope).

**Comment by BoatsAreRockable** [comment]
Okay I misunderstood. As long as it continues to function in #22 then I should be able to adjust the CSS as necessary in order to make sure it actually overlays the live video feed.
