### ISSUE TITLE
Automatically create the output folder if needed

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/animator#27]
If an output folder is set but does not actually exist, the path should be created and the user notified (use `notifyInfo()`) so frames can be saved/deleted.

**Comment by BoatsAreRockable** [comment]
Can new directories not already be created via the directory selection dialogue?

**Comment by le717** [comment]
That does not matter. If for some reason that path no longer exists (read: it gets pulled out from under BA), we attempt to wrote to a non-existent path so no frames are saved. It should be automatically created, which is expected behavior.

**Comment by le717** [comment]
(Also technically this would be classified as a bug, not enhancement.)

**Comment by BoatsAreRockable** [comment]
Oh I didn't understand, reclassified it as a bug.

**Comment by le717** [comment]
@BoatsAreRockable Would you like to fix this one?

**Comment by BoatsAreRockable** [comment]
Yeah I think I could give this a go.

**Comment by le717** [comment]
I found a new bug resulting from the fix for this in #102 but I'll file a new issue for that.
