### ISSUE TITLE
Make fullscreen default

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#31]
I think that Boats Animator should start Fullscreen on first load. While this is personal preference, it's actually much more logical. Animators want to see the frame preview as large as they possibly can, and if it starts fullscreen, it will simply make it easier to use, instead of having to fullscreen it every time/

**Comment by BoatsAreRockable** [comment]
I will implement this as soon as I've made some CSS improvements to the program's appearance at larger window sizes

**Comment by rioforce** [comment]
I guess that'll do, though, on my laptop the fullscreen looks great, but IDK what it'll look like on larger screens.

I might fork this and play with some css if you'd like. It might not come to anything, but it's worth a shot, haha.

**Comment by BoatsAreRockable** [comment]
I think I've made the necessary CSS adjustments to make a maximised window (different to a full screen one) suitable as the default window size.
