### ISSUE TITLE
Splash screen has a scroll bar

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#32]
Another nit-pick I have is the new splash screen. I like how you have news and stuff, but it's annoying that it has a scroll bar, but there's a big blue space on the left side. I think that the news should probably be inside the blue sidebar. It will separate Project Tools from the News, and make the entire thing easier to use. The less scroll bars the better, IMO. ;)

**Comment by BoatsAreRockable** [comment]
Yeah recent projects should probably be the main focus and that second scroll bar definitely has to go!

**Comment by BoatsAreRockable** [comment]
The news feed still needs to be reimplemented. Either the previous script will be used but in an iframe for performance reasons or as a twitter feed.
