### ISSUE TITLE
Combine Live Preview and Playback boxes

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#33]
Not that this is priority at all, or even necessary, but it's something that I thought I'd mention anyway. In my opinion, there should only be one box that displays frames. Basically, combine the live preview and the playback boxes. This makes the interface simpler and more streamlined. It would work a lot like Dragonframe. Here's how:

On the right side of the frame timeline (at the bottom), there is a "Live Preview" button stuck there (the horizontal scroll-bar doesn't affect it). If someone clicks on a previously captured frame, it will preview that frame instead of the live frame. Playing the video will do the same thing, it just covers up the live frame. When someone clicks the Live Preview button, it will get rid of the playing video or the previewing frame, and show the live view again, onion skinning and all.

Of course this is just personal preference, but to me it seems quite logical, instead of having two preview boxes.

**Comment by BoatsAreRockable** [comment]
Having 2 separate windows was mostly done to make things easier for the initial implementation but I agree one window makes for a cleaner UI. I wonder if this would be something users would like an option to choose between in the preferences.

**Comment by rioforce** [comment]
Personally, I think an option isn't needed. It would create problems for you coders, and I doubt it's really necessary, seeing as only one screen is only looked at at a time anyway. It's up to you though.

**Comment by BoatsAreRockable** [comment]
It's true that such an option would create a few headaches. I think I will try the one window layout out

**Comment by BoatsAreRockable** [comment]
Closed as implemented.
