### ISSUE TITLE
Splash Screen URL does not open in web browser

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#36]
On the splash screen, when you click the Charlielee.uk link, it opens a new Boats Animator window to load the website. This isn't good practice, because then someone cannot bookmark it and stuff like they would in a web browser. It should open the link in the default web browser instead.

**Comment by BoatsAreRockable** [comment]
Ah yes I was aware of this, it should definitely be fixed. Thank you for all of these issues btw they are absolutely the best feedback that can be given at this stage!
