### ISSUE TITLE
Change icons to use FontAwesome?

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#41]
I've been looking in the files, and I see you are using various PNG files for the in-program icons. I was thinking that we might want to consider using FontAwesome for these instead, because it is much more flexable than images.

For example, it only has to load the font once, it acts like text so you can color scale and such easily, and it is actually probably smaller in file size than png images. There's even a few animated icons for loaders and such.

Though, this is just personal preference. It might make it where you cannot add icons in the menu bar, so that's a minus. I was just curious what you thought about that.

Here's their website:
https://fortawesome.github.io/Font-Awesome/icons/

Alternatively, we can use the .SVG versions of the icons from flaticon, which will allow a bit more ease for scaling the images. Either way, we do need to not use PNG files, we should be using vectors or a font. ;)

**Comment by BoatsAreRockable** [comment]
The PNGs that are currently been used are only a few KBs each - similar that of the SVGs. Changing to SVGs would be pretty simple and indeed should be done to ensure BA looks good for users of high DPI displays etc. 

FontAwesome looks interesting however Flaticon does in fact offer a very similar font-based option. As a result it is more of a question of whether the appearance of FontAwesome icons or the current Flaticon ones is better.

For now I will definitely change the current PNGs to SVGs and leave open the question of whether we should move to a font/css based solution for the icons.

**Comment by le717** [comment]
> For now I will definitely change the current PNGs to SVGs and leave open the question of whether we should move to a font/css based solution for the icons.

I think that question has been answered. :P

**Comment by BoatsAreRockable** [comment]
Yep :laughing:
