### ISSUE TITLE
Make icon font local

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#46]
This is an issue for way later. FontAwesome is currently pulling from the web, so the icons won't appear on offline testing. Once we get all the icons we need, we'll need to build a custom package of fontawesome and upload it to the repo to be packaged with the program.

Of course, if you chose not to use FontAwesome, then this doesn't specifically apply, but it will apply if you chose to use any other icon font. ;)

**Comment by BoatsAreRockable** [comment]
I'm happy with the FontAwesome icons that are currently being used. Will have to remember about building the custom package when the time comes!

**Comment by BoatsAreRockable** [comment]
@le717 added a local copy of Font Awesome in #58. It is a full copy so a custom package still needs to eventually be made.

**Comment by le717** [comment]
Because the goal of this issue (have a local copy of the icon font) has been fulfilled, it should be closed and a new issue documenting a custom copy should be filed.
