### ISSUE TITLE
Click frames in framereel to show frame preview

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#47]
When one clicks a frame in the framereel, it needs to show up in the preview box. It also needs to have a little border around the icon in the framereel so the user knows what frame they currently have selected.

In the StatusBar, the "Current frame" also needs to reflect the frame that is currently selected.

**Comment by BoatsAreRockable** [comment]
I shall look to implement this. May take a while as playback will need modifying to allow starting from a particular frame.

**Comment by le717** [comment]
Let me handle this one. I am currently reworking playback so I'll be able to redesign it with this in mind.

**Comment by BoatsAreRockable** [comment]
Alright then, thanks a lot! :smiley:
