### ISSUE TITLE
Live View button issues

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#48]
* [ ] The live view button should not toggle between live and preview. When a frame on the framereel is selected, it will go to the preview frame, but if the live view button is selected, it will go to the live view.

* [ ] When the user is on live view mode, the live view icon needs to have a border around it, similar to that of when a frame is selected on the framereel.

* [x] The live view button is currently on the left side of the framereel, when it needs to be on the right, just like a frame on the framereel, it scrolls.

* [x] The live view button is also the wrong size, for some reason. 

* [x] The Live View button also needs a hover-title so people know what the button is.

Of course, this depends on if you keep the live view button the way it is. You mentioned you didn't think it was very good, but maybe it just needs a bit of help? We can discuss this. ;)

###### *Edited by BoatsAreRockable to make the bullet points into check boxes*

**Comment by BoatsAreRockable** [comment]
I think it will be alright once it is moved to the far right of the frame reel and has a clear selected effect. I've added the current mode to the status bar to make it obvious which mode the user is in.

**Comment by le717** [comment]
I have fixed a few of theses myself, will be in my next PR.

**Comment by le717** [comment]
The remaining two items will be fixed once #90 is merged.
