### ISSUE TITLE
Alert boxes should be converted to notifications with buttons on them

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#49]
Alert boxes look very intrusive at the time being, not really matching the program. I was thinking that they could be converted into notifications with buttons on them (Notifications that don't go away until you click on it).

Either that or Alert boxes need better styling.

**Comment by BoatsAreRockable** [comment]
The only alert boxes that are currently being used are for features that are yet to be implemented - these are certainly temporary.

You probably mean the confirm box that appears when the user deletes a frame, I agree that this are very intrusive and should be redone with some sort of custom solution. You should also be able to press "enter" to confirm deleting the frame to save saving the user from using the mouse.

**Comment by rioforce** [comment]
Whoops, yeah, I meant confirm boxes not alert.

**Comment by BoatsAreRockable** [comment]
I'm currently working on this

**Comment by BoatsAreRockable** [comment]
Implemented in https://github.com/BoatsAreRockable/animator/commit/2a542c5feaf880f25e3fd894055e21150820b904. The implementation of custom confirm boxs eventually needs further work mentioned near the end of #70

**Comment by BoatsAreRockable** [comment]
Closed as implemented. The need to eventually revise this is in  #82
