### ISSUE TITLE
Missing app.nw file

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/animator#5]
I downloaded NW.js to run the program in it, when I realized there is no app.nw file like the readme says to open.

**Comment by BoatsAreRockable** [comment]
Opps! The app.nw files are quite straight forward to create, simply move the app folder's contents to a ZIP folder and rename the file extension of this folder to .nw

Thank you for your help generally - you can probably tell that I am rather new to JavaScript with this project's main purpose being to help me improve my JS abilities.
