### ISSUE TITLE
Placeholder div needs to be in place when switching between live view and frame preview

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#50]
When switching between live preview and frame preview, this is a bit of lag-time where nothing is shown in the frame-space. There needs to be some type of placeholder div (with the same responsiveness as the video and frame boxes) to hold the place of the frame so the interface doesn't break while switching.

**Comment by BoatsAreRockable** [comment]
This has been fixed with commit https://github.com/BoatsAreRockable/animator/commit/26a47bad019342f5dfc4f9c7a5997c2692ea14b5
