### ISSUE TITLE
Launching the animator from the launcher shouldn't use the same window

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/animator#52]
Currently, when you load the launcher, and you click the New Project button, it simply resizes the launcher window and changes the content. This is bad because, 1) it has the "File, Edit, Capture, Help" menus on the launcher, which don't do anything there, 2) it causes problems later when projects are implemented, the animator window doesn't just need to change to a launcher, it should load a new launcher window (and vise versa), 3) the window looks crazy while it is switching between programs

**Comment by BoatsAreRockable** [comment]
Agreed, these should be separate windows.
