### ISSUE TITLE
Frame reel images display back to front

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#55]
This was a major bug that I accidentally created with https://github.com/BoatsAreRockable/animator/commit/26a47bad019342f5dfc4f9c7a5997c2692ea14b5

**Comment by BoatsAreRockable** [comment]
I've changed the frame reel to how it was before. @le717 this is the problem I was initially trying to fix:
[Imgur](http://i.imgur.com/rjjlgLZ.png?1)

**Comment by BoatsAreRockable** [comment]
It wasn't documented, but @rioforce's #63 fixes the problem with the live preview button displaying in the wrong place! Thank you :smile:

**Comment by rioforce** [comment]
Oh yeah, haha, I forgot to mention that in my commit.
