### ISSUE TITLE
Restyle launcher screen

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/animator#57]
It should follow the same design as the animator.

**Comment by rioforce** [comment]
I'll tackle this soon

**Comment by BoatsAreRockable** [comment]
<img width="638" alt="launcherdemo" src="https://cloud.githubusercontent.com/assets/8095888/11198382/3ff59e42-8cbc-11e5-9c52-a7cbfdd7b295.png">

I've begun working on this. As well as matching the dark theme I've made it so that new and recent projects are combined. The red /  green / pink areas would eventually be a thumbnail from the project it represents.

**Comment by BoatsAreRockable** [comment]
Some of the things I'm still to do:
- [] Make recent projects fill area fully.
- [] Sort out news area margins.

Here's the branch I'm working from:
https://github.com/BoatsAreRockable/animator/tree/restyle-splash

**Comment by rioforce** [comment]
Wow, looks good. However, the Open Project button looks a bit left out.

Question, what happens if someone makes a project without a frame, what will it show for the thumbnail?

I was basically thinking that it would just be a list, but that works too. Though, instead of showing how many frames it has, maybe it should say how many takes it has?

How many recent files would you allow to be on the home screen? I'd think it wouldn't go over four.

**Comment by BoatsAreRockable** [comment]
Yes the window could do with being a bit smaller. I agree that no of takes would probably be more helpful than no of frames in the bottom right of the thumbnails. Additional info such as no of frames could be displayed when the user hovers / clicks on a thumbnail.

For projects without any frames I guess some sort of neutral gray colour background would be the thumbnail.

Unless there's performance reasons I don't see a reason for a low limit to the number of recent files. On opening only the first few files would be visible with some sort if "view more" link to expand the number of files visible. 

These expanded files could be split into sections for last week, last month, last year and older. This is similar to how the music program Sibelius's launcher works. I'll try I get a screenshot to show what I mean here in the morning.

I quite like my thumbnail design but I think it would be pretty neat if the launcher could have the ability  to switch between "thumbnail" and "list" views. The user could set their preferred default view in the eventual preferences window.

Also the dates I've used are DD/MM/YY, the ability to switch to MM/DD/YY dates would have to be considered for you Americans! (If we choose to keep the dates in the current format of course)

**Comment by rioforce** [comment]
Sounds like a plan! I especially like the idea of toggling between a list and the thumbnails. I can't wait to try this out when it becomes more final-ish. I actually started working on my own today, haha, but yours is so much better, I'll leave it to you.

BTW, just thought I'd mention that since the launcher's html file has no need to be called index, it probably shouldn't be. It should probably be called `launcher.html` instead, to designate itself as the launcher.

**Comment by le717** [comment]
OK, yea... I definitely have a few remarks to make on this... Also, be sure to @ mention me when you put up a PR for a code review.

**Comment by BoatsAreRockable** [comment]
Sure thing.

**Comment by le717** [comment]
OK, where do I start…

I like the changes. They look very nice and certainly match the rest of the UI Good job there. :+1:

That being said, I don’t think this is going to be technically possible. Not technically as in technicality, but as in the code side of things. Let me explain.

1. You are implement a UI for something (projects) that cannot be started on until _at least_ January, if not even later. Until everything project related is added, those are dummy icons for months. Not good.

2. This will be a coding nightmare. Think about all opening a project involves. Read the JSON, update all values, load all the frames. Depending on project size, this could be very resource intensive. Now think about having to do all this on app load, in addition to keeping a list of all recently opened projects with that file keeping track of the info the project file would not. We have just parsed the same content _twice_ one the project has been opened. And since the first one runs on app load, even 4 items may cause a long app loading time (file I/O and DOM interaction is not cheap). All this requires some super complicated coding, one that may look nice in design but will be ugly in implementation.

3. Switching between list and icon… With that, we will have to remove everything we built from the DOM and rebuild completely different HTML. Oh, ideally we’d cache all this rebuilding on every switch would be super slow. We’d have to store the last used view. Oh, and if we open a different project in the Animator then go back to the launcher we have to figure out what project has not been built and build it for displaying.

I am sorry if this is coming off as harsh, as that is not my intention at all. Please do not take this personally. Constrictive criticism over code is not is not to be taken personally. Good people can write bad code. You are learning quickly and that is good. :smiley: However, you are lacking forethought and thorough thinking. Your design, while on paper looks good, will be a coding nightmare.

I  would suggest something like Dragonframe’s launcher: logo, a list of recent projects (only their names displayed) which open it, and an open button. The code for it would be _much_ cleaner and simpler, and it can be made to look just as nice. Your current design, though, is a code disaster and introduces too much unneeded complexity for such a small app.

**Comment by BoatsAreRockable** [comment]
Yes, that does sound rather complicated! I shall endeavour to scale this back to simply a list of the projects.

**Comment by BoatsAreRockable** [comment]
<img width="556" alt="launcherdemo3" src="https://cloud.githubusercontent.com/assets/8095888/11324913/3b827cf2-9137-11e5-960e-22df668b0eab.png">

Finished scaling back to purely a list view. @le717 I hear what you've said about having dummy / placeholder projects being bad practise so once we're happy with the appearance of the recent projects area I'll set it to `display:none`.

Shall create a pull release now.

**Comment by le717** [comment]
BTW, do not tag a release yet. It is not yet time. :)
