### ISSUE TITLE
Windows Installer Solutions

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#72]
Obviously this is something that isn't at all a priority, but for the best user experience on Windows the program should eventually be available in the form of an installer. I've been looking at a couple of solutions with [Inno Setup](http://www.jrsoftware.org/isinfo.php#features) being very easier to implement but limited in features and [Advanced Installer](http://www.advancedinstaller.com/free-license.html) being very powerful indeed!

Advanced Installer is usually pretty pricey but they appear to offer [free licenses](http://www.advancedinstaller.com/free-license.html) for open source projects. I've been playing playing around with the program's trial and am quite impressed. This seems like a feature that would really give Boats Animator a professional touch. Is there any obvious reason why I should not get in touch with them for a license?

The main reason I could see against doing this is a question of the necessity of an installer.

**Comment by rioforce** [comment]
I've only used Inno, never Advanced Installer. If it works well, I don't see any reason not to use it. Of course, as long as it works really well, like uninstalling all of the files, and vital good installer things like that. Of course, it depends on their license. If it conflicts with our Open Source license, and we cannot host the installer script, that causes a problem.

Of course, we want to also provide a standard ZIP package for portable installations.

**Comment by BoatsAreRockable** [comment]
After some further investigation Inno Setup does not appear to be as basic as I first thought. One major issue I initially saw with it was the lack ability to use custom themes but someone appears to have developed an addon to allow this: http://isskin.codejock.com/

A couple of advantages I see of Advanced Installer are the ability to create .MSI files and how it handles installing updated versions. I'd like to investigate whether these are possible in Inno. 

I'm coming to the conclusion that Advanced Installer is probably overkill for our needs, especially if InnoSetup can be custom skinned, however, I shall have do even more research before commiting to one or the other.

**Comment by rioforce** [comment]
Not sure why you'd need an MSI file, an exe is just fine, really. But yeah, Inno is advanced enough for our needs. The scripting and, as you mentioned, the plugin will help. I suppose you can do some experimentation with it and see if it can suit your needs, then we can decide based on the facts.

**Comment by BoatsAreRockable** [comment]
This addon may have tipped the balance to Inno: https://www.kymoto.org/products/inno-script-studio

I have used it a tiny bit in the last will do some testing of it tomorrow. Yes you're right the advantages to generate MSIs don't affect us here (ignore my previous comment... :smiley:)

**Comment by le717** [comment]
I will further comment on this later, but my $0.02 for now:

Inno Setup is :+1:. I've used it for ages, very good software. I especially love Inno Script Studio, very good IDE. MSIs are pretty much useless in our case. 99% of the time, themes are unnecessary, complicated to setup, use, and compile with and bloat the installer. Maybe this is a 1%, we'll see. Even without a complete custom theme, we can change the BMP graphics used, which is usually all that is needed.

**Comment by BoatsAreRockable** [comment]
I continue to be impressed by Inno Setup today, I believe it is the solution we should use. I'd like the setup scripts to be available on GitHub for scrutiny and will be adding them shortly.

**Comment by BoatsAreRockable** [comment]
I've added Inno Setup Scripts for v0.6.1 in 5161ea7dddb12e6a29f308ee4188c3007729549b. The installers these produce have been added to the v0.6.1 [release page](https://github.com/BoatsAreRockable/animator/releases/tag/v0.6.1)

**Comment by le717** [comment]
This can be closed now that we have a Windows installer.
