### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#77]
Currently `(C) Charlie Lee 2015` is displayed in both the animator and menu windows. I have a 2 part question regarding this:

1) Is it standard for this information to be prominent in such a way, would it be better for it to be displayed in the menu window, not at all or on a separate about page?

2) Boats Animator is an open source project and this copyright attribution was added before I created this GitHub repository. Since there have been major contributions by others is saying that the program is `Copyright Charlie Lee` strictly no longer true and a bit inconsiderate to the other contributors?

Obviously this is an issue that would potentially be slightly awkward for anyone other than myself to bring up but I really want to make sure that I'm doing things properly and that the current and future contributors to BA get the credit they deserve.

**Comment by rioforce** [comment]
I have no idea how the copyright works with GPL, but I assume that the copyright for the base of the program still applies.

However, in most programs I use, there isn't attribution at the bottom of the screen. On Help>About, you can make a new window that has credits on it, as well as some contribution info.

**Comment by le717** [comment]
Per point 2: I think it is fine. You are the creator and primary dev. If you want, it could be changed to say something like "2016 Boats Animator Contributors". 

Fixed by #123, closing.
