### ISSUE TITLE
Remove individual frame delete buttons

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/animator#83]
Spun off #73.

> The delete frame button on each frame in the framereel should go away, because it seems too easy to accidentally click. The main delete button would work better, because ideally, when you delete a frame, it automatically previews the next frame, thus, if someone was deleting many frames in a row, they wouldn't need to move their mouse, just click delete over and over again.

**Comment by BoatsAreRockable** [comment]
One thought I had with this feature is that it if would be nice if the undo button only showed in capture mode and it was replaced by the delete button in playback mode.

**Comment by le717** [comment]
I like that idea. Will implement.

**Comment by le717** [comment]
Remove this from any milestone for now. The individual buttons currently works just fine for now, and I'd like to go ahead and submit this camera-related code. We will fix this, just not right now.

**Comment by le717** [comment]
"Fixed" (more like nullified) by #124. Closing.
